const apps = [
  {
    id: 1,
    appName: 'GPay - Secure Payments',
    brand: 'gpay',
    packageName: 'com.google.android.apps.nbu.paisa.user',
    developer: 'Google LLC',
    iconHash: 'a1b2c3d4',
    nameSimilarity: 1.0,
    packageSimilarity: 1.0,
    developerMatch: true,
    riskScore: 5,
    isGenuine: true,
    permissions: ['SMS', 'Contacts', 'Location'],
    reviewKeywords: ['easy', 'fast', 'secure'],
  },
  {
    id: 2,
    appName: 'GPay - UPI Payments & Recharge',
    brand: 'gpay',
    packageName: 'com.gpay.payment.rewards.offers',
    developer: 'GPay Services',
    iconHash: 'a1b2c3d5',
    nameSimilarity: 0.9,
    packageSimilarity: 0.6,
    developerMatch: false,
    riskScore: 85,
    isGenuine: false,
    permissions: ['SMS', 'Contacts', 'Location', 'Read External Storage', 'Write External Storage'],
    reviewKeywords: ['scam', 'fake', 'money lost', 'fraud'],
  },
  {
    id: 9,
    appName: 'GPay - Payments & Recharge',
    brand: 'gpay',
    packageName: 'com.gpay.payment.offers',
    developer: 'GPay Corporation',
    iconHash: 'a1b2c3d6',
    nameSimilarity: 0.9,
    packageSimilarity: 0.9,
    developerMatch: false,
    riskScore: 95,
    isGenuine: false,
    permissions: ['SMS', 'Contacts', 'Location', 'Read External Storage', 'Write External Storage','Camera','Audio'],
    reviewKeywords: ['scam', 'fake', 'money lost', 'fraud','Extortion'],
  },
  {
    id: 3,
    appName: 'PhonePe: UPI, Recharge & Bill Payment',
    brand: 'phonepe',
    packageName: 'com.phonepe.app',
    developer: 'PhonePe',
    iconHash: 'e5f6g7h8',
    nameSimilarity: 1.0,
    packageSimilarity: 1.0,
    developerMatch: true,
    riskScore: 3,
    isGenuine: true,
    permissions: ['SMS', 'Location', 'Contacts'],
    reviewKeywords: ['good', 'convenient', 'works well'],
  },
  {
    id: 4,
    appName: 'PhonePe - Get Daily Rewards',
    brand: 'phonepe',
    packageName: 'com.phonepe.rewards.cashback',
    developer: 'PhonePe Apps',
    iconHash: 'e5f6g7h9',
    nameSimilarity: 0.85,
    packageSimilarity: 0.5,
    developerMatch: false,
    riskScore: 92,
    isGenuine: false,
    permissions: ['SMS', 'Location', 'Contacts', 'Camera', 'Record Audio'],
    reviewKeywords: ['cheating', 'not working', 'stole my data'],
  },
  {
    id: 5,
    appName: 'Paytm: Secure UPI Payments',
    brand: 'paytm',
    packageName: 'net.one97.paytm',
    developer: 'Paytm - One97 Communications Ltd.',
    iconHash: 'i9j0k1l2',
    nameSimilarity: 1.0,
    packageSimilarity: 1.0,
    developerMatch: true,
    riskScore: 4,
    isGenuine: true,
    permissions: ['Location', 'Contacts', 'SMS'],
    reviewKeywords: ['useful', 'fast', 'reliable'],
  },
  {
    id: 6,
    appName: 'Paytm Wallet - Instant Money',
    brand: 'paytm',
    packageName: 'net.one97.paytm.wallet',
    developer: 'Paytm Entertainment',
    iconHash: 'i9j0k1l3',
    nameSimilarity: 0.8,
    packageSimilarity: 0.7,
    developerMatch: false,
    riskScore: 78,
    isGenuine: false,
    permissions: ['Location', 'Contacts', 'SMS', 'Read Accounts', 'Access Photos'],
    reviewKeywords: ['adware', 'crashes', 'fake app'],
  },
  {
    id: 7,
    appName: 'Cred',
    brand: 'Cred',
    packageName: 'com.dreamplug.androidapp.',
    developer: 'CRED-FinTech',
    iconHash: 'c2r5d3f6',
    nameSimilarity: 1.0,
    packageSimilarity: 1.0,
    developerMatch: true,
    riskScore: 5,
    isGenuine: true,
    permissions: ['SMS', 'Contacts', 'Location'],
    reviewKeywords: ['easy', 'fast', 'secure'],
  },
  {
    id: 8,
    appName: 'Cred',
    brand: 'Cred',
    packageName: 'com.dreampluck.androidapp.',
    developer: 'CREED-FinTech',
    iconHash: 'c2r5d3f7',
    nameSimilarity: 0.8,
    packageSimilarity: 0.7,
    developerMatch: false,
    riskScore: 65,
    isGenuine: false,
    permissions: ['SMS', 'Contacts', 'Location','File','Camera'],
    reviewKeywords: ['Extortion', 'Phishing', 'Scam'],
  }
];

module.exports = apps;
